Fixed almost all Webhint warnings and added accessibility
Kakalanp/Portfolio-Joaquin pull request #9
Opened 2022-01-18 17:46 UTC by Kakalanp

Most Webhint warnings were “noreferrer” missing on “a” tags. Added the “noreferrer” property to “rel” inside most “a” tags.

Added a little spacing in the “head” of the page, just for comfort when reading it.

Added explicit but short “alt” descriptions inside important images.

Removed useless “alt” descriptions that may be disorienting for people with screen readers.

Removed fixed height of 95vh from the landing page container, as it served no propose and caused some visual overlap of text at zoom 500%*

2022-01-18 19:39 UTC, ShinobiWarior requested changes
## Hi @Kakalanp @mauriciomonta  👋🏼 , 

### STATUS: Changes requested! ♻️ ♻️ ♻️ 

You did a solid job so far! 👏🏼 

However, there are some issues that you still need to work on to go to the next project but you are almost there!
Please pay attention about instructions how to make changes on your code. It should not be done directly but by opening a new branch and linking the changes you did to your report. 😉 


![image](https://c.tenor.com/26f7XoUC1AIAAAAd/so-close-jim-halpert.gif)


## Required Changes ♻️
_Check the comments under the review._



- [ ]  Please make sure that you include links to your changes:

- If you needed to change something, [link to the corresponding line of code in your pull request changes](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148).
- Instead of this list you created
![image](https://user-images.githubusercontent.com/63932912/150000834-cfc4382c-e306-4f78-84fe-d33618a04cf9.png)
you just need to add link to the line in your code you changed near the point it refers to.
For example: 
- Page titles: [Change 1](https://github.com/Kakalanp/Portfolio-Joaquin/blob/921f9356d310899390bce290196e9b5ffaa5f3ed/index.html#L14-L16)

- [ ] Please make sure that you have only 1 `<h1>` tag on your page and that it stands on the top of your page - [headings](https://www.w3.org/WAI/test-evaluate/preliminary/#headings);
![image](https://user-images.githubusercontent.com/63932912/150004167-689bf041-a673-44a5-80d0-9b986c7691a9.png)
![image](https://user-images.githubusercontent.com/63932912/150004254-12ea5974-666c-4c0f-8b15-c4e8dd9b5429.png)

- [ ] Please make sure that the page has a minimum contrast ratio of at least 4.5:1 for normal-size text.You can use [this aditus tool](https://www.aditus.io/button-contrast-checker/) to help checking the color contrast of the project.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-18 19:39 UTC, ShinobiWarior commented on index.html
> +                    <a target="_blank" href="https://www.twitter.com/LeccaJoaquin"  rel="noopener noreferrer"><img src="https://img.icons8.com/ios-glyphs/30/000000/twitter--v1.png" alt="Twitter profi
[Required]
- [ ] Please make sure that you added links to your changes into your report as it was required in project instructions.

[Optional] 

- [ ] You can revert those commits and make changes on a new branch. Then you can add link to changes from that branch to your report on this branch.

2022-01-18 19:39 UTC, ShinobiWarior commented on index.html
>                  </li>
[Required]
- [ ] Same like for all other changes - please make sure that you added links to your changes into your report as it was required.

[Optional] 

- [ ] You can revert those commits and make changes on a new branch. Then you can add link to changes from that branch to your report on this branch.

2022-01-18 21:58 UTC, Kakalanp commented
> * Please make sure that the page has a minimum contrast ratio of at least 4.5:1 for normal-size text.You can use [this aditus tool](https://www.aditus.io/button-contrast-checker/) to help checking the color contrast of the project.

About this part, I'm a little confused with the color change, I'm using the colors from the Figma design, should I change those to whatever contrasts no matter the color nor the Figma-template-fidelity?

2022-01-18 22:34 UTC, ShinobiWarior commented
Hey @Kakalanp , the only thing you should do there is to change the shade of your buttons. For example instead of `.button { background: #36b37f }` you can use some darker shade like this one `#2b8e65`. If you are using Firefox browser I would recommend you to install [this addon](https://addons.mozilla.org/en-US/firefox/addon/wcag-contrast-checker/) so in combination with developer tools you can find the good shade of color.

2022-01-18 23:19 UTC, Kakalanp commented
> the only thing you should do there is to change the shade of your buttons

Thank you for the clarification! 🔍 

I just updated everything you pointed out, and I'm about to submit my project for another review, many thanks for your help! 😁

2022-01-18 23:26 UTC, ShinobiWarior commented
> > the only thing you should do there is to change the shade of your buttons
> 
> Thank you for the clarification! 🔍
> 
> I just updated everything you pointed out, and I'm about to submit my project for another review, many thanks for your help! 😁

You are very welcome. I am glad to help. Please, don't forget to add links to corresponding changes before you submit for another review. 😉

2022-01-19 00:08 UTC, Kakalanp commented
I just did, I'm not sure if it's too much, but it surely passes the requirements.

2022-01-19 00:31 UTC, Meltrust approved these changes
Hi @Kakalanp, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-19 14:12 UTC, merged